/*
 * This source file was generated by the Gradle 'init' task
 */
package jlox;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

public class Lox {
    static boolean hadError = false;

    public static void main(String[] args) throws IOException {
        if (args.length > 1) {
            System.out.println("Usage: jlox [script]");
            System.exit(64);
        } else if (args.length == 1) {
            runFile(args[0]);
        } else {
            runPrompt();
        }
    }

    private static void runFile(String path) throws IOException {
        /**
         * 명령줄에서 파일 경로를 지정하여 jlox 실행
         */
        byte[] bytes = Files.readAllBytes(Paths.get(path));
        run(new String(bytes, Charset.defaultCharset()));

        if (hadError)
            System.exit(65); // 프로그램을 실행하다가 오류가 발생하면 종료
    }

    private static void runPrompt() throws IOException {
        /**
         * 대화형 프롬프트(REPL)로 jlox 실행
         */
        InputStreamReader input = new InputStreamReader(System.in);
        BufferedReader reader = new BufferedReader(input);

        for (;;) {
            System.out.print("> ");
            String line = reader.readLine();
            if (line == null)
                break;
            run(line);
            hadError = false; // REPL이 중단되지 않도록 hadError 플래그 리셋
        }
    }

    private static void run(String source) {
        Scanner scanner = new Scanner(source);
        List<Token> tokens = scanner.scanTokens();

        for (Token token : tokens) {
            System.out.println(token);
        }
    }

    static void error(int line, String message) {
        report(line, "", message);
    }

    private static void report(int line, String where, String message) {
        /**
         * 에러가 발생한 코드 라인을 알려주는 함수.
         * 에러를 일으킨(generate) 코드와 알리는(report) 코드는 서로 분리하는 것이 좋은 엔지니어링 프랙티스다.
         * 상이한 리포팅 전략을 바꿔가며 적용할 수 있도록 ErrorReporter 같은 인터페이스로 추상화하여 스캐너와 파서에 전달하는 것이 가장
         * 좋다.
         */
        System.err.println("[line " + line + "] Error" + where + ": " + message);
        hadError = true;
    }
}
